name: Swift

on:
  release:
    types:
      - "published"

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
      - name: Change version
        run: sed "s/VERSION/${{github.ref_name}}/g" ./Sources/wicli/entry.swift
      - name: Build
        run: swift build -c release --arch arm64 --arch x86_64
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ".build/apple/Products/Release/wicli"